# cBioMOL - open C++ and Python platform for BioMOLecular visualization and analysis
# -------------------------------------------------------------------
# This file contains source code for the cBioMOL computer program
# Copyright (C) 2026 Hannah Kullik, Martin Urban (hannah.kullik@studmail.w-hs.de, martin.urban@studmail.w-hs.de)
# Source code is available at <https://github.com/urban233/cBioMOL>
# -------------------------------------------------------------------
# It is unlawful to modify or remove this copyright notice.
# -------------------------------------------------------------------
# Please see the accompanying LICENSE file for further information.
# -------------------------------------------------------------------
# Primary author of this source file:
# Martin Urban
# -------------------------------------------------------------------
# Additional authors of this source file include:
#
# ==============================================================================
"""Controller for the new Chat Canvas UI, wiring the AI worker using the thread API."""

from __future__ import annotations

import logging
import threading
from typing import Any
from typing import Callable

from pymol_copilot.ai.app.models.plan_parser import PlanParser
from pymol_copilot.ai.app.models.session import PlanStep
from pymol_copilot.ai.backend.config import InferenceConfig
from pymol_copilot.ai.backend.protocol import InferenceBackend
from pymol_copilot.ai.execution.execution_worker import ExecutionWorker
from pymol_copilot.ai.explanations import explain_plan
from pymol_copilot.ai.inference import prompt_builder
from pymol_copilot.ai.inference.conversation import Conversation
from pymol_copilot.gui.qt import QtCore
from pymol_copilot.gui.qt.thread import background_task
from pymol_copilot.gui.qt.widgets.conversation_canvas import AgentCancelledCard
from pymol_copilot.gui.qt.widgets.conversation_canvas import AgentThinkingCard
from pymol_copilot.gui.qt.widgets.conversation_canvas import PlanApprovalCard
from pymol_copilot.gui.qt.widgets.conversation_canvas import UserRequestCard
from pymol_copilot.gui.qt.widgets.panel import PmlCopilotPanel

__docformat__ = "google"

LOGGER = logging.getLogger(__name__)


@background_task
def run_inference(
    prompt: str,
    conversation: Conversation,
    config: InferenceConfig,
    cancel_event: threading.Event,
    backend: InferenceBackend,
    progress_callback: Callable[[int, str], None] | None = None,
) -> str:
    """Run inference in the background, streaming tokens.

    Args:
        prompt: User's prompt.
        conversation: State of the conversation.
        config: Inference configuration.
        cancel_event: Event to cancel processing.
        backend: The inference backend to use.
        progress_callback: Callback to stream tokens.

    Returns:
        The full output generated by the assistant.

    Raises:
        RuntimeError: If prompt context size is exceeded.
        InterruptedError: If generation is cancelled.
    """
    conversation.append_user(prompt)

    while True:
        tmp_prompt = prompt_builder.build_prompt(
            conversation, prompt_family=config.prompt_family
        )
        tmp_budget = prompt_builder.estimate_token_budget(tmp_prompt)
        if tmp_budget <= config.n_ctx - config.max_tokens:
            break
        if len(conversation.turns) <= 1:
            raise RuntimeError("Prompt prefix exceeds context window.")
        del conversation.turns[0:2]

    def _on_token(delta: str) -> None:
        """Forward tokens to the progress callback.

        Args:
            delta: The new token string.
        """
        if progress_callback:
            progress_callback(0, delta)

    tmp_output = backend.stream_completion(
        tmp_prompt,
        cancel_event,
        _on_token,
    )

    if cancel_event.is_set():
        raise InterruptedError("Generation cancelled.")

    conversation.append_assistant(tmp_output)
    return tmp_output


class ChatController(QtCore.QObject):
    """Orchestrates the Chat UI Canvas with the inference backend."""

    def __init__(
        self,
        panel: PmlCopilotPanel,
        config: InferenceConfig,
        execution_worker: ExecutionWorker | None = None,
        parent: QtCore.QObject | None = None,
    ) -> None:
        """Initialize the ChatController.

        Args:
            panel: The new Copilot panel to control.
            config: Configuration for AI inference.
            execution_worker: Optional worker for PyMOL execution.
            parent: Optional Qt parent.
        """
        super().__init__(parent)
        self._panel = panel
        self._config = config
        self._execution_worker = execution_worker

        self._parser = PlanParser()
        self._conversation = Conversation()
        self._backend: InferenceBackend | None = None
        self._cancel_event = threading.Event()
        self._thinking_card: AgentThinkingCard | None = None
        self._cancelled_card: AgentCancelledCard | None = None

        self._wire_panel()
        if self._execution_worker:
            self._wire_execution()

    def _wire_panel(self) -> None:
        """Connect UI signals from the panel."""
        self._panel._input_bar.submitted.connect(self._on_user_submit)
        self._panel._input_bar.stopRequested.connect(self.request_cancel)

    def _wire_execution(self) -> None:
        """Connect UI signals from the execution worker."""
        if not self._execution_worker:
            return
        self._execution_worker.signals.execution_finished.connect(
            self._on_execution_finished
        )
        self._execution_worker.signals.execution_failed.connect(
            self._on_execution_failed
        )

    def _init_backend(self) -> None:
        """Load the inference backend if not already loaded."""
        if self._backend is None:
            if self._config.mock:
                import pymol_copilot.ai.backend.mock_engine as mock_engine

                self._backend = mock_engine.MockEngine()
            else:
                import pymol_copilot.ai.backend.llama_engine as llama_engine

                self._backend = llama_engine.LlamaEngine()
            self._backend.load(self._config)

    def _on_user_submit(self, text: str) -> None:
        """Handle a new user prompt submission.

        Args:
            text: The text entered by the user.
        """
        self._cancel_event.clear()
        self._parser.reset()

        tmp_user_card = UserRequestCard(text)
        self._panel._cui_canvas.add_card(tmp_user_card)

        self._thinking_card = AgentThinkingCard()
        self._panel._cui_canvas.add_card(self._thinking_card)

        try:
            self._init_backend()
        except Exception as tmp_exc:
            LOGGER.error("Failed to load backend: %s", tmp_exc)
            if self._thinking_card:
                self._thinking_card.stop()
            return

        if self._backend is None:
            return

        tmp_job = run_inference(
            prompt=text,
            conversation=self._conversation,
            config=self._config,
            cancel_event=self._cancel_event,
            backend=self._backend,
        )
        tmp_job.on_progress(self._on_token)
        tmp_job.on_success(self._on_inference_success)
        tmp_job.on_error(self._on_inference_error)
        tmp_job.start()

    def _on_token(self, percentage: int, delta: str) -> None:
        """Handle streamed tokens.

        Args:
            percentage: Ignored percentage value.
            delta: The new token string.
        """
        self._parser.feed(delta)

    def request_cancel(self) -> None:
        """Request cancellation and immediately show the cancelling card."""
        self._cancel_event.set()
        if self._thinking_card:
            self._thinking_card.stop()
            self._thinking_card.hide()
            self._thinking_card.deleteLater()
            self._thinking_card = None
        self._cancelled_card = AgentCancelledCard()
        self._panel._cui_canvas.add_card(self._cancelled_card)

    def _on_inference_success(self, output: str) -> None:
        """Handle successful completion of inference.

        Args:
            output: The generated text output.
        """
        self._panel._input_bar.set_processing(False)
        if self._thinking_card:
            self._thinking_card.stop()
            self._thinking_card.hide()
            self._thinking_card.deleteLater()
            self._thinking_card = None

        tmp_steps, tmp_prose = self._parser.finalize()
        tmp_explained = explain_plan(tmp_steps)

        if not tmp_explained:
            return

        tmp_step_texts = [step.display_label for step in tmp_explained]
        tmp_plan_card = PlanApprovalCard(
            title="Generated Plan",
            steps=tmp_step_texts,
        )
        tmp_plan_card.approved.connect(
            lambda approved_texts: self._on_plan_approved(
                tmp_explained, approved_texts
            )
        )
        self._panel._cui_canvas.add_card(tmp_plan_card)

    def _on_plan_approved(
        self, all_steps: list[PlanStep], approved_texts: list[str]
    ) -> None:
        """Handle plan approval.

        Args:
            all_steps: Original generated steps.
            approved_texts: Step texts that were approved.
        """
        if not self._execution_worker:
            return

        tmp_accepted_steps = [
            step for step in all_steps if step.display_label in approved_texts
        ]
        self._execution_worker.submit(tmp_accepted_steps)

    def _on_inference_error(self, exc: Exception, tb: str) -> None:
        """Handle an error during inference.

        Args:
            exc: The exception instance.
            tb: Formatted traceback string.
        """
        LOGGER.error("Inference error: %s\n%s", exc, tb)
        self._panel._input_bar.set_processing(False)
        if self._thinking_card:
            self._thinking_card.stop()
            self._thinking_card.hide()
            self._thinking_card.deleteLater()
            self._thinking_card = None
        if isinstance(exc, InterruptedError) and self._cancelled_card:
            self._cancelled_card.stop()
            self._cancelled_card = None

    def _on_execution_finished(self, log_lines: list[str]) -> None:
        """Handle successful execution of steps.

        Args:
            log_lines: Log outputs from execution.
        """
        pass

    def _on_execution_failed(self, step_index: int, message: str) -> None:
        """Handle execution failure.

        Args:
            step_index: Index of the failing step.
            message: The failure message.
        """
        pass
