load("@rules_python//python:py_test.bzl", "py_test")

py_test(
    name = "command",
    srcs = ["test_command.py"],
    main = "test_command.py",
    deps = [
        "//src/pmc_client:pmc_client",
        "//src/pmc_core:pmc_core",
    ],
)

py_test(
    name = "subsystem_imports",
    srcs = ["test_subsystem_imports.py"],
    main = "test_subsystem_imports.py",
    deps = [
        "@pypi//pytest",
        "//src/pmc_agent:pmc_agent",
        "//src/pmc_core:pmc_core",
        "//src/pmc_data:pmc_data",
        "//src/pmc_train:pmc_train",
    ],
)

py_test(
    name = "loopback_transport",
    srcs = ["test_loopback_transport.py"],
    main = "test_loopback_transport.py",
    deps = [
        "@pypi//pytest",
        "//src/pmc_client:pmc_client",
        "//src/pmc_core:pmc_core",
        "//src/pmc_server:pmc_server",
    ],
)
