load("@rules_python//python:py_test.bzl", "py_test")

py_test(
    name = "plan",
    srcs = ["test_plan.py"],
    main = "test_plan.py",
    deps = [
        "@pypi//pytest",
        "//src/pmc_core:pmc_core",
    ],
)

py_test(
    name = "policy",
    srcs = ["test_policy.py"],
    main = "test_policy.py",
    deps = [
        "@pypi//pytest",
        "//src/pmc_core:pmc_core",
    ],
)

py_test(
    name = "policy_sabotage",
    srcs = ["test_policy.py", "test_policy_sabotage.py"],
    main = "test_policy_sabotage.py",
    deps = [
        "@pypi//pytest",
        "//src/pmc_core:pmc_core",
    ],
)

py_test(
    name = "protocol",
    srcs = ["test_protocol.py"],
    main = "test_protocol.py",
    deps = [
        "@pypi//pytest",
        "//src/pmc_core:pmc_core",
    ],
)

test_suite(
    name = "all",
    tests = [":plan", ":policy", ":policy_sabotage", ":protocol"],
)
